-- Add AI analysis columns to fivi_sessions table
ALTER TABLE public.fivi_sessions
ADD COLUMN IF NOT EXISTS ai_transcription text,
ADD COLUMN IF NOT EXISTS ai_summary text,
ADD COLUMN IF NOT EXISTS ai_sentiment_analysis jsonb,
ADD COLUMN IF NOT EXISTS ai_commitments text[],
ADD COLUMN IF NOT EXISTS ai_concerns text[],
ADD COLUMN IF NOT EXISTS ai_confidence_score integer,
ADD COLUMN IF NOT EXISTS ai_key_points jsonb,
ADD COLUMN IF NOT EXISTS ai_processed_at timestamp with time zone;

-- Add comment for documentation
COMMENT ON COLUMN public.fivi_sessions.ai_transcription IS 'Full audio transcription by AI';
COMMENT ON COLUMN public.fivi_sessions.ai_summary IS 'Executive summary generated by AI';
COMMENT ON COLUMN public.fivi_sessions.ai_sentiment_analysis IS 'Sentiment analysis JSON with overall mood, score, indicators and evolution';
COMMENT ON COLUMN public.fivi_sessions.ai_commitments IS 'Array of commitments extracted from conversation';
COMMENT ON COLUMN public.fivi_sessions.ai_concerns IS 'Array of concerns/blockers identified';
COMMENT ON COLUMN public.fivi_sessions.ai_confidence_score IS 'Confidence score 0-100 for the salesperson';
COMMENT ON COLUMN public.fivi_sessions.ai_key_points IS 'Key points organized by category (achievements, challenges, opportunities, suggested_actions)';
COMMENT ON COLUMN public.fivi_sessions.ai_processed_at IS 'Timestamp when AI processing was completed';